module.exports = {
  name: 'Holdem.Tech',
  prefix: 'holdemTech',
  footerText: 'HoldemTech © 2017',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7000'],
  openPages: ['/login', '/reg'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/user/login',
    userReg: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    posts: '/posts',
    user: '/user/:id',
    dashboard: '/dashboard',
  },

  lang: 'chs',
};